language: node_js
node_js:
- stable
dist: precise
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_install:
- sudo apt-get update
- sudo apt-get install python3
script:
- yarn test
deploy:
- provider: script
  script: yarn deploy:prod
  on:
    branch: master
env:
  global:
  - secure: K91vNxSqbfDh0gyCTEGhJBmXka7aXdLl7xy3NqJ5wo+M1ufGf+G1LiJBGmGBw5LnI4cnloTAbCINQ9HXvgBS3qUayEFXl5iMRcXhx0MvdkNUM1seiKvGupu2z2RCqmIQCdYI+V5sSiMooZgTAMP1S3giK4gfzPogizgS8s1Xbm4JF2mBCMs50BEam2Mydv/7ju2Git9jsb5pyqoRPCSUdq7sIlq1QffUp22u9PWKZ4eNUtlWlj2gTBkMRLbGFEPTdc6DiH4AhwkqKK1/XjoBN20vMo+UsyOZ7ENxNT+k3JNE7GHOmZfaJbx42xikX0mK3end8f4kFNqUEbItQPLvbZN609MxMGvOyyazrUgBmdJOOE/oDbE9qcTkl6gZeJW86FwRgcQstbqfno0hrb5q9SMKCX29VEvHDj74tTDmUuyTz+8OV4YMtbCEsp3Pa6q6ZZHEdJzNuSeFGDvDMSkGQXSTDm4TttE4k64HrOm7c0x2gizheGscExTiBGK/vOx7d2thJTD0ti730hLpLZ/ZLcvitNLm3gwOmwgaKGAjunVfKoyYMNhdAS0SMkczcirGil7c03HFipIcHIL9O7Re12wWb0vqA4a6KP/kix3yMRLZTouWI+IqQgt3gIt4G6nQUjTqZMvHFVqP6IhtWwugClOBIUPqTKFX3XZJsmQFjIQ=
  - secure: O9d6NNU+9Jo4jdMaeNCVvqpYazgK86W+cG0TPcHPKQAiikn8/sqahkqPwLKXLPDLQpNgkuAtmzc2rFl67e08Tab2kY6bh56pm1nMW0l8DiUHrk4jCAFU+xJoAQ0umo5ZgsbGJNjn0m/31hC7vRfMC6QIGGgCpGt73spiPjP/uMremUEefRRzi3A+mlC+VuOQm0amiFGZo8ej0EV/RgBRo4MZ24Uhgp05s84or4ckz0nt2aZu0ASPDGbo9cC9lqMVtwHOPWpAnYd+2jgjoEayhYXzvcW9RzS6kvrA3r3z/D6aOz5cvbyX9GjyQY1ao00h2jQQ0GOUjGTtw4CBeVlnv2g1Is79iaLkhEku74idVWLDgHb4xqQ2DrRbBquJAU/3EcgKkIz2l6aJuSPBmHP4pApgKMIup9XNU2QO5QXL2PJyj264rV+1U+aJmUT2lV6rhcI5tyUbyZEFAypbrJjqQ8AVS6YxKFU55GFdb1//hOnwctHdmY2Fma4SS17fW7FKzx1dYypYSCVvUPhhh1M3IbiaFEI7rsjsr9YM3Ry935Q9pNLrGC/jAhjegaTSJSbedKD3nMg8TWUgIzrn3mpGwmTuf3KdliKQ5PKd898OpJH64560din00rbJSii2tApXJQDwU4LyYtsvKfT/tsPsY9dOgUxn423JffNo5zqyGhE=
